name: Deployment

on:
  push:
    branches: ["master"]

permissions: write-all

jobs:
  build:
    # Specify runner + deployment step
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: hm2-infrastructure

    steps:
      - uses: actions/checkout@v3
        with:
          lfs: true
      - name: Use Node.js 16
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: "npm"
          cache-dependency-path: hm2-infrastructure/package-lock.json
      - run: npm ci
      - run: npm run build
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: ./hm2-infrastructure/dist
